services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinic_management_app
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: production
      PORT: 5000
    volumes:
      - clinic_uploads:/app/server/uploads

volumes:
  clinic_uploads:
